; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
upload_port = COM3
upload_protocol = stlink

[env:nucleo_f401re_cube]
board = nucleo_f401re
framework = stm32cube
board_upload.maximum_ram_size = 98304
platform = ststm32

; Das hier zwingt PlatformIO, ALLES zu scannen:
lib_ldf_mode = deep+

; Early build script for VFP configuration
extra_scripts = scripts/extra_script.py

; Board-Spezifische Flags
board_build.f_cpu = 84000000L

build_flags =
    -Iinclude
    -Ilib/ST_AI_Lib/include
    -Lsrc
    -lNetworkRuntime1020_CM4_GCC.a
    -lm
    -larm_cortexM4lf_math
    -mthumb
    -march=armv7e-m
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    ${env.build_flags}
    -Wl,-u_printf_float
    -Wl,--defsym=LD_MAX_STACK_SIZE=1024
    -Wl,--defsym=LD_MAX_HEAP_SIZE=1024

monitor_port = COM3
monitor_speed = 115200